# Generated by Django 4.0.5 on 2022-06-22 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_percentage', models.IntegerField()),
                ('coupon_code', models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Earring', 'Earring'), ('Necklace', 'Necklace'), ('Ring', 'Ring'), ('Bracelet', 'Bracelet')], default='NotDefined', max_length=10)),
                ('name', models.CharField(max_length=100)),
                ('price', models.FloatField()),
                ('image', models.URLField()),
                ('dimension', models.CharField(max_length=10)),
                ('weight', models.FloatField()),
                ('material', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=500)),
                ('in_wishlist', models.BooleanField()),
                ('in_cart', models.BooleanField()),
                ('offers', models.ManyToManyField(to='api.offer')),
            ],
        ),
    ]
